# Generated by Django 5.0.2 on 2024-03-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizador', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.TextField()),
                ('presupuesto', models.CharField(max_length=100)),
                ('cantidad_personas', models.CharField(max_length=100)),
            ],
        ),
    ]
