# Generated by Django 5.0.2 on 2024-03-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_tbl',
            name='presupuesto',
            field=models.FloatField(max_length=100),
        ),
    ]
